### ISSUE TITLE
IMAP storage Capacity

### ISSUE THREAD

**Issue by RedSoxFan04** [micz/ImapQuota#3]
In the dialog box, under the Quota tab, the allotted storage of the IMAP account is stated in kilobytes. Nowadays, email accounts often provide gigabytes of storage. According to ImapQuota, Google provides 120 gigabytes of email storage - though I had to use DuckDuckGo to convert kilobytes to gigabytes to find that out. I'd really like it if ImapQuota either exclusively showed IMAP storage in gigabytes or provided a choice of units.

**Comment by micz** [comment]
For locale strings: https://hg.mozilla.org/l10n-central/en-GB/file/tip/mail/chrome/messenger/messenger.properties#l503
Need to fully replace the locale tooltip message: https://hg.mozilla.org/l10n-central/en-GB/file/tip/mail/chrome/messenger/messenger.properties#l503

**Comment by micz** [comment]
Fixed in https://github.com/micz/ImapQuota/commit/71cf8e402e7af1acdbe82221cd2125241b0c0fb3.
It will be released in version 1.2.
