### ISSUE TITLE
Support for Thunderbird 68

### ISSUE THREAD

**Issue by dillenger** [micz/ImapQuota#7]
This is a legacy webextension for Thunderbird 68+. You can use it if you want.
I know you suspended development for this, if  you don't want to use it I'll probably fork it.

[imapquota@micz.it-2.0-tb.zip](https://github.com/micz/ImapQuota/files/3413215/imapquota%40micz.it-2.0-tb.zip)

**Comment by micz** [comment]
There is no need to fork it. If you like, I could add you as contributor here on github and also on the Thundebird Addon site, so you could maintain it directly.
I've already done this for other extensions when someone stepped up to help.
Let me know.
Thanks.

Mic

**Comment by dillenger** [comment]
That's ok with me too, I'm still figuring out how github works but ATN wouldn't be a problem.
The username on Mozilla is my email address, here on github it is dillenger.

Cheers,

Michel

**Comment by micz** [comment]
Done!
Thank you for your help.

Mic
