### ISSUE TITLE
Show quota for account in virtual forlders too

### ISSUE THREAD

**Issue by tooomm** [micz/ImapQuota#8]
I really miss that the quota is not shown in virtual folders in the status bar.

As these are the folders I use 90% of the time and only check the inbox and other folders if there really is a special need.
I would love to don't miss out on the important quota information to take needed steps not only when it's too late.

**Comment by dillenger** [comment]
Impossible, virtual folders exist only on your computer and can not have quota set.

**Comment by tooomm** [comment]
That's true.
But if they only check folders within one mail account - that's how I use it - then it could show that accounts quota.

I have virtual folders setup for each mail account individually.
