### ISSUE TITLE
Quota status doesn't refresh properly (delayed, slow update)

### ISSUE THREAD

**Issue by tooomm** [micz/ImapQuota#9]
I cleaned my mailbox up recently.
Even after deleting and clearing the trash bin, the display didn't update. In the webmail of my provider the changes showed right away.

It took quite a while until the display in the status bar refreshed itself.
And I couldn't initiate that process myself via e.g. right click --> update/refresh/check option.

How does the refresh process work? When is it run and the display value updated?

**Comment by dillenger** [comment]
Typical end user issue, has nothing to do with this extension which only displays the information it gets from Thunderbird. Please use the user forums for this type of questions.
Nevertheless, next time, try File > Compact Folders. You can change the settings for automatic compacting in Preferences > Advanced > Network & Disk Space.

**Comment by tooomm** [comment]
I'm sorry if this is the wrong place? I was not aware.
If the extension only displays information already available in TB itself without generating or querying that information for itself, then this is obviously nothing the addon can easily change.


Will do some research on how the compact folders feature works and what it exactly does. Thank you
